name: Generate Embeddings

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
      - '**/*.mdx'

jobs:
  generate-embeddings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Generate embeddings
        run: npm run generate-embeddings
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

